**Ques1**

In [36]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)
print("a) Adding 2:", arr + 2)
print("b) Multiplying by 3:", arr * 3)
print("c) Dividing by 2:", arr / 2)

Original array: [10 20 30 40 50]
a) Adding 2: [12 22 32 42 52]
b) Multiplying by 3: [ 30  60  90 120 150]
c) Dividing by 2: [ 5. 10. 15. 20. 25.]


**Ques2**

In [37]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original array:", arr)
print("a) Reversed array:", arr[::-1])
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
print("b) Array x: Most frequent value:", most_frequent)
print("Indices:", np.where(x == most_frequent)[0])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
print("b) Array y: Most frequent value:", most_frequent)
print("Indices:", np.where(y == most_frequent)[0])

Original array: [1 2 3 6 4 5]
a) Reversed array: [5 4 6 3 2 1]
b) Array x: Most frequent value: 1
Indices: [0 5 7 8 9]
b) Array y: Most frequent value: 1
Indices: [0 1 2]


**Ques3**

In [38]:
import numpy as np
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(arr[0, 1])
print(arr[2, 0])

20
70


**Ques4**

In [39]:
import numpy as np
Muskaan_Singhal = np.linspace(10, 100, 25)
print("Array:")
print(Muskaan_Singhal)
print("Dimensions:", Muskaan_Singhal.ndim)
print("Shape:", Muskaan_Singhal.shape)
print("Total elements:", Muskaan_Singhal.size)
print("Data type:", Muskaan_Singhal.dtype)
print("Total bytes:", Muskaan_Singhal.nbytes)
transpose_array = Muskaan_Singhal.reshape(1, 25)
print("Transpose using reshape:")
print(transpose_array)
print(Muskaan_Singhal.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


**Ques5**

In [40]:
import numpy as np
Muskaan_Singhal = np.array([[10, 20, 30, 40],
                            [50, 60, 70, 80],
                            [90, 15, 20, 35]])
print("Original array:")
print(Muskaan_Singhal)
print("Mean:", np.mean(Muskaan_Singhal))
print("Median:", np.median(Muskaan_Singhal))
print("Maximum:", np.max(Muskaan_Singhal))
print("Minimum:", np.min(Muskaan_Singhal))
print("Unique elements:", np.unique(Muskaan_Singhal))
resized_Muskaan_Singhal = np.resize(Muskaan_Singhal, (2, 3))

print("Resized array:")
print(resized_Muskaan_Singhal)

Original array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Resized array:
[[10 20 30]
 [40 50 60]]
